name: Build Snake Game

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Install Raylib
      run: choco install raylib -y

    - uses: actions/checkout@v2

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile Source Code
      run: cl.exe main.cpp /I"C:\Program Files (x86)\raylib\include" /EHsc /Fe:snake.exe /link /LIBPATH:"C:\Program Files (x86)\raylib\lib" raylib.lib opengl32.lib gdi32.lib winmm.lib
